AllCops:
  TargetRubyVersion: 2.3

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  Enabled: False

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericPredicate:
  Enabled: False
  # EnforcedStyle: comparison

Style/Documentation:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300
